---
kind: pipeline
type: docker
name: default

steps:

###
### Mirror the current repository state to Github
###

- name: github-mirror
  image: alpine
  environment:
    SSH_PUBKEY:
      from_secret: ssh_pubkey
    SSH_PRIVKEY:
      from_secret: ssh_privkey

  commands:
    - . .drone/github-mirror.sh

###
### Run a smoke test of the application by trying a full build
###

- name: build
  image: node:current-alpine3.20
  commands:
    - . .drone/build-all.sh
